### PR TITLE
Make multi-root configurable

### LINKED ISSUE #6: Server starts up with multiple workspace folders with no instruction to do so
When I start up a new project with pyright, the log shows that "workspaceFolders" in the log has many entries. I'm not sure how these are being set but it slows down the project with file watchers.

Any thoughts?  It looks like these are every paths to every python project I've ever run this in. Could it be reading my projectile bookmarks?

Screen Shot 2020-07-28 at 10 34 45 PM

### PR DESCRIPTION
**Pull request by zeronone**
Fixes #6

### CODE REVIEW

**Comment by jsigman** [comment]
Oddly enough, this branch does not address the problem, does anyone else see this?

**Comment by jsigman** [comment]
> Oddly enough, this branch does not address the problem, does anyone else see this?

Sorry. This is wrong. It does fix the problem. The custom variable `lsp-pyright-multi-root` must be set before the package is loaded.

**Comment by steven-lang** [comment]
Also note, that setting `lsp-pyright-multi-root` to `nil` may have no effect until the `lsp-session-file` was manually removed, or else the lsp session will always load the stored list of workspaces from that file which was created when `lsp-pyright-multi-root` was `t`.

**Comment by kuchichan** [comment]
@steven-lang I have exactly the same thoughts as you do. I have tried literally everything, separate projectile projects, separate treemacs workspaces, but still it works as you described. Ofc when the observed projects adds up it could have the impact on performance, the only way I found is to literally remove workspace folders by hand, which is annoying.

**Comment by anupam312nwd** [comment]
> > Oddly enough, this branch does not address the problem, does anyone else see this?
> 
> Sorry. This is wrong. It does fix the problem. The custom variable `lsp-pyright-multi-root` must be set before the package is loaded.

Hi, I am having this issue too. Can you tell me how should I set this variable before the package is loaded.
I tried:
```
(use-package lsp-pyright
  :defer t
  :init
  (setq lsp-pyright-multi-root nil)
  :config
  (setq lsp-pyright-python-executable-cmd "python3")
  )
```
but it did not fix the issue. Thanks!

**Comment by seagle0128** [comment]
@anupam312nwd Try `:custom` keyword?

**Comment by anupam312nwd** [comment]
> @anupam312nwd Try `:custom` keyword?

Thanks! The same code worked after a few restarts of Emacs and deleting `lsp-workspaces` manually. 
I had tried `:custom` keyword too. This too worked.

**Pull request merged**
