### PR TITLE
Support travis ci.

### PR DESCRIPTION
**Pull request by seagle0128**
Initial commit for travis ci.

See #1.

### CODE REVIEW

**Comment by zeronone** [comment]
Thanks a lot for doing this.

The builds for `26.1, 26.2` is failing. Is it expected?

**Comment by seagle0128** [comment]
It wired to get this error on 26.1 and 26.2: "Package ‘spinner-1.7.3’ is unavailable". Will re-trigger.

**Comment by seagle0128** [comment]
I found the root cause. GNU ELPA keyring should be updated for 26.1 and 26.2. Already update, but need to squash and merge.

**Comment by seagle0128** [comment]
@zeronone Please review. Squash and merge it if you think it's fine. I tested and it looks good.

**Pull request merged**
